[mypy]
strict = True
python_version = 3.14
warn_return_any = True
warn_unused_ignores = True

[mypy-keenyspace_shared.*]
ignore_missing_imports = True

[mypy-apscheduler.*]
ignore_missing_imports = True

[mypy-joserfc.*]
ignore_missing_imports = True

[mypy-testcontainers.*]
ignore_missing_imports = True
